name: 'GoodReadMe'
description: 'Keep your ReadMe up to date'
author: 'Vova Stelmashchuk <goodreadme@androidstory.dev>'
inputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'green'
  icon: 'check'
