name: 'GoodReadMe'
description: 'Keep your ReadMe up to date'
author: 'Vova Stelmashchuk <goodreadme@androidstory.dev>'
inputs:
  service_host:
    description: 'Base url to service'
    required: false
    default: 'http://goodreadme.androidstory.dev'
  client_secret:
    description: 'Client secret'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service_host }}
    - ${{ inputs.client_secret }}
branding:
  color: 'green'
  icon: 'check'
